# Generated by Django 4.1.7 on 2023-03-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('queue_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('puuid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('summoner_name', models.CharField(max_length=255, unique=True)),
                ('level', models.IntegerField()),
                ('profile_icon_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchhistory.champion')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchhistory.match')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchhistory.summoner')),
            ],
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='matchhistory.participant')),
                ('win', models.BooleanField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('gold_earned', models.IntegerField()),
                ('total_damage_dealt', models.IntegerField()),
                ('total_damage_taken', models.IntegerField()),
                ('creep_score', models.IntegerField()),
                ('items', models.ManyToManyField(to='matchhistory.item')),
            ],
        ),
    ]
