# Generated by Django 4.1.7 on 2023-03-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchhistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='season_id',
        ),
    ]
