# Generated by Django 4.1.7 on 2023-03-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchhistory', '0002_remove_match_season_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='icon_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
