# Generated by Django 4.1.7 on 2023-03-29 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchhistory', '0003_summoner_icon_image_url_alter_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='champion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matchhistory.champion'),
            preserve_default=False,
        ),
    ]
